stages:
    - dotnetbuild
     
dotnet-build:
    image: microsoft/dotnet:2.1
    stage: dotnetbuild
    tags:
        - dotnet
    script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
        - dotnet build

    