stages:
    - dotnetbuild
    - angularbuild
    - dotnetdeploy
     
dotnet-build:
    stage: dotnetbuild
    tags:
        - dotnet
    script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
        - dotnet build
        
dotnet-deploy:
    stage: dotnetdeploy
    tags:
        - dotnet
    script:
        - sudo systemctl MyVirtualCloset-backend stop
        - sudo systemctl MyVirtualCloset-backend start

angular-build:
    image: trion/ng-cli
    stage: angularbuild
    tags:
        - angular
    script:
        - cd Frontend/MyVirtualCloset
        - npm install --silent
        - ng build --prod
    