stages:
    - dotnetbuild
    - angularbuild
    - dotnettest
    - angulartest
    - dotnetdeploy
    - angulardeploy
     
dotnet-build:
    stage: dotnetbuild
    tags:
        - shell
    before_script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
    script:
        - dotnet build
        
dotnet-test:
    stage: dotnettest
    tags:
        - shell
    before_script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
    script:
        - dotnet test
    after_script:
        - sudo docker system prune --volumes -f -a
        
dotnet-deploy:
    stage: dotnetdeploy
    only:
        - master
    tags:
        - shell
    before_script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
        - sudo systemctl daemon-reload
    script:
        - dotnet publish -c release -r linux-x64 --self-contained
        - sudo mv ./MyVirtualCloset/bin/Release/netcoreapp2.1/linux-x64/publish/* /var/www/MyVirtualCloset
        - sudo chmod +x /var/www/MyVirtualCloset/MyVirtualCloset.Api
        - sudo systemctl stop MyVirtualCloset-backend
        - sudo systemctl start MyVirtualCloset-backend

angular-build:
    stage: angularbuild
    tags:
        - shell
    before_script:
        - cd Frontend/MyVirtualCloset
        - npm install
    script:
        - ng build --prod
        
angular-test:
    image: trion/ng-cli-karma
    stage: angulartest
    tags:
        - angular
    before_script:
        - cd Frontend/MyVirtualCloset
        - npm install
    script:
        - ng test
        
angular-deploy:
    stage: angulardeploy
    only:
        - master
    tags:
        - shell
    before_script:
        - cd Frontend/MyVirtualCloset
        - npm install
    script:
        - ng build --prod
        - sudo rm /var/www/html/ -rf *
        - sudo mv ./dist/MyVirtualCloset/* /var/www/html/