stages:
    - dotnetbuild
    - angularbuild
    - dotnetdeploy
     
dotnet-build:
    stage: dotnetbuild
    tags:
        - dotnet
    script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
        - dotnet build
        
dotnet-deploy:
    stage: dotnetdeploy
    tags:
        - shell
    script:
        - dotnet publish -c release --self-contained
        - sudo systemctl stop MyVirtualCloset-backend
        - sudo systemctl start MyVirtualCloset-backend

angular-build:
    image: trion/ng-cli
    stage: angularbuild
    tags:
        - angular
    before_script:
        - cd Frontend/MyVirtualCloset
        - npm install
    script:
        - ng build --prod
    