stages:
    - dotnetbuild
    - angularbuild
     
dotnet-build:
    stage: dotnetbuild
    tags:
        - dotnet
    script:
        - cd Backend/MyVirtualCloset
        - dotnet restore
        - dotnet build

angular-build:
    image: trion/ng-cli
    stage: angularbuild
    tags:
        - angular
    script:
        - cd Frontend/MyVirtualCloset
        - npm install --silent
        - ng build --prod
    